### ISSUE TITLE
PyPI's latest version is very old

### ISSUE THREAD

**Issue by jbouvier** [resmio/django-sendgrid#21]
The latest version that's available on PyPI is 0.3.0. Can you please push the latest release to PyPI so that it can be easily installed?

**Comment by chickahoona** [comment]
Hi, The pypi package is unmaintained, yet you can install this package from github by including it into your requirements.txt with this line:

```
-e git+https://github.com/resmio/django-sendgrid.git@v1.0.2#egg=django-sendgrid-webhook
```
